global:
  podSecurityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000
  containerSecurityContext:
    allowPrivilegeEscalation: false
    runAsUser: 1000
    runAsNonRoot: true

installer:
  repo: "Shivam-nagar23/devtron"
  release: "v0.6.16"
  image: "quay.io/devtron/inception"
  tag: "44b30917-185-13275"
  
components:
  dashboard:
    image: "quay.io/devtron/test:6b8dc81b-2553-3892"
  devtron:
    image: "quay.io/devtron/test:d11804fb-2551-3894"
    cicdImage: "quay.io/devtron/test:d11804fb-2551-3894"
  argocdDexServer:
    image: "ghcr.io/dexidp/dex:v2.30.2"
    initContainer:
      authenticator: "quay.io/devtron/authenticator:e414faff-393-13273"
  kubelink:
    image: "quay.io/devtron/kubelink:18bf720b-318-13404"
  postgres:
    image: "quay.io/devtron/postgres:11.9.0-debian-10-r26"
    armImage: "quay.io/devtron/postgres:11.9"
  
  migrator:
    image: "quay.io/devtron/migrator:ec1dcab8-149-13278"
    envVars:
      devtron:
        GIT_BRANCH: "main"
        GIT_HASH: "260f871f3a8fe3f11a2c414aaa8861d3be7ab8aa"
      casbin:
        GIT_BRANCH: "main"
        GIT_HASH: "260f871f3a8fe3f11a2c414aaa8861d3be7ab8aa"
        
argo-cd:
  global:
    image:
      repository: quay.io/argoproj/argocd
      tag: "v2.5.2"
      imagePullPolicy: IfNotPresent

security:
  imageScanner:
    image: "quay.io/devtron/test:759270d8-2530-3895"

notifier:
  image: "quay.io/devtron/notifier:6c7a356a-372-11107"
