global:
  podSecurityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000
  containerSecurityContext:
    allowPrivilegeEscalation: false
    runAsUser: 1000
    runAsNonRoot: true

installer:
  repo: "Shivam-nagar23/devtron"
  release: "v0.6.16"
  image: "quay.io/devtron/inception"
  tag: "44b30917-185-13275"
  
components:
  dashboard:
    image: "quay.io/devtron/test:4d85725b-2553-5251"
  devtron:
    image: "quay.io/devtron/test:787f5d77-298-2676"
    cicdImage: "quay.io/devtron/test:787f5d77-298-2676"
  argocdDexServer:
    image: "ghcr.io/dexidp/dex:v2.30.2"
    initContainer:
      authenticator: "quay.io/devtron/authenticator:e414faff-393-13273"
  kubelink:
    image: "quay.io/devtron/kubelink:18bf720b-318-13404"
  postgres:
    image: "quay.io/devtron/postgres:11.9.0-debian-10-r26"
    armImage: "quay.io/devtron/postgres:11.9"
  
  migrator:
    image: "quay.io/devtron/migrator:ec1dcab8-149-13278"
    envVars:
      devtron:
        GIT_BRANCH: "main"
        GIT_HASH: "4724dc4278f59d0398438d19552ec158aa05ebbf"
      casbin:
        GIT_BRANCH: "main"
        GIT_HASH: "4724dc4278f59d0398438d19552ec158aa05ebbf"
        
argo-cd:
  global:
    image:
      repository: quay.io/argoproj/argocd
      tag: "v2.5.2"
      imagePullPolicy: IfNotPresent

security:
  imageScanner:
    image: "quay.io/devtron/test:fc36c8a7-297-2674"

notifier:
  image: "quay.io/devtron/notifier:6c7a356a-372-11107"
